version: '3'
services:
  database:
    image: "postgres:13.2"
    env_file:
      - database.env
    ports:
      - 5433:5432
    volumes:
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data: